services:

  postgres:
    image: postgres:16-alpine
    container_name: agrobodega-postgres
    environment:
      POSTGRES_DB: agrobodega
      POSTGRES_USER: agrobodega_user
      POSTGRES_PASSWORD: agrobodega_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U agrobodega_user -d agrobodega" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: agrobodega-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  kong:
    image: kong:3.6-ubuntu
    container_name: agrobodega-kong
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /kong/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
    ports:
      - "8000:8000"
      - "8001:8001"
    volumes:
      - ./kong:/kong
    restart: unless-stopped
    depends_on:
      - postgres

  vault:
    image: hashicorp/vault
    container_name: agrobodega-vault
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: agrobodega-token
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    ports:
      - "8200:8200"
    restart: unless-stopped

volumes:
  postgres_data: